### ISSUE TITLE
Error with candidates

### ISSUE THREAD

**Issue by ghost** [nathanrooy/differential-evolution-optimization-with-python#3]
Good day,

I tried to implement the DE optimization in Python but I got the following error:
canidates.remove(j)
AttributeError: 'range' object has no attribute 'remove'

Could you please assist me, I am not sure what went wrong.

Kind regards
Carike

**Comment by giacom0c** [comment]
Hi, this code was probably designed for Python 2.x, because at that time the range function returned a list. Now with Python 3.x we have a range object, which does not have the remove (and many others) method, since now is an Iterator (and NOT a list).
To update the code for Python 3.x just convert that object to a list:

`canidates = list(range(0,popsize))`

PS: we should also fix "canidates" to "candidates" :P

**Comment by nathanrooy** [comment]
Thanks @G0D0T
